# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 02:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import signin.models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000000), django.core.validators.MinValueValidator(999999999), signin.models.phone_exists]),
        ),
    ]
