# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20180104_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
