# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import signin.models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_profile_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[signin.models.phone_regex, signin.models.phone_exists, signin.models.unique_signin]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='outreach',
            field=models.CharField(blank=True, choices=[('web', 'Website'), ('flyer', 'Flyer'), ('friend', 'Friend'), ('walk', 'Walked by'), ('other', 'Other')], max_length=6, null=True, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Your phone number will be used to sign in', max_length=10, null=True, unique=True, validators=[signin.models.phone_regex]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_experience',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, verbose_name='Have you meditated before?'),
        ),
    ]
